### ISSUE TITLE
how to change the value of val_batch_size?

### ISSUE THREAD

**Issue by zouyanmei** [guochengqian/PointNeXt#102]
Thanks for your share. I found that the value of val_batch_size is been set to 1. How can I do to change the value of val_ batch_size? Thanks!

**Comment by yuchenlichuck** [comment]
Hi, there! When you run the script of any experiments you can indicate `val_batch_size`
e.g, `CUDA_VISIBLE_DEVICES=0 python examples/shapenetpart/main.py --cfg cfgs/s3dis/pointnext-s.yaml val_batch_size=8`

**Comment by zouyanmei** [comment]
> Hi, there! When you run the script of any experiments you can indicate `val_batch_size` e.g, `CUDA_VISIBLE_DEVICES=0 python examples/shapenetpart/main.py --cfg cfgs/s3dis/pointnext-s.yaml val_batch_size=8`

Thanks, but I can not train the model with val_batch_size=20. Below is my result.
![sunlogin_20230124225846](https://user-images.githubusercontent.com/45259702/214329959-2e4fe8c6-587c-420a-b790-cf6824db0b7e.jpg)

**Comment by yuchenlichuck** [comment]
I see, from my understanding, you are using dataset scannet or s3dis as evaluation. As far as I know, during the validation, because the room scene is so big and the number of point clouds in each room is different, it can't be read in batch. you can check the code in the `s3dis` dataset and `segmentation` file for further detail.
