### ISSUE TITLE
mIoU about S3DIS. 

### ISSUE THREAD

**Issue by Elbenhorn** [guochengqian/PointNeXt#108]
Thank your amazing work!
I noticed that the mIoU in your released log is 70.08 which is different from 71.11 declared in the Model zoo. Could you tell me why they are different?

**Comment by yuchenlichuck** [comment]
Thank you for your question, it is a good question. The training mode's data loading differs from the test mode because of the test speed, in test mode, we load the whole room at the same time while during the training process, it samples for some points during the training. 71.1 result we got is from test mode. You can use our pre-trained model and use test mode to obtain it. Thank you
