### ISSUE TITLE
about Scannetv2 semantic segmentation

### ISSUE THREAD

**Issue by lcysonya** [guochengqian/PointNeXt#28]
Hi~ Thanks for the great work again :)

I use your framework to try semantic segmentation on Scannetv2, same data process and training setting.  Since the pointnext achieve the top1 mIoU on s3dis, I except the results on Scannetv2 also higher than others.  Actually, compare with top3 **validation** mIou, about 72-73, the results I got from pointnext-XL only around 68.8.

Did you try on scannetv2?  What's your conclusion?  Why the improvements on s3dis seems not work  well on scannetv2 or maybe other datasets?

**Comment by guochengqian** [comment]
Dear Liu,

We will release code on ScanNetv2 soon. We reach around 72 mIoU. There are some differences due to some parameters are dataset specific.

1. Voxel max 64000
2. Radius 0.05
3. LR 0.001
4. Multistep decay as stratified transformer

This code will be released after about three days. Now i am very busy with Neurips rebuttal.



On Aug 5, 2022, at 05:09, Congying liu ***@***.***> wrote:

﻿

Hi~ Thanks for the great work again :)

I use your framework to try semantic segmentation on Scannetv2, same data process and training setting. Since the pointnext achieve the top1 mIoU on s3dis, I except the results on Scannetv2 also higher than others. Actually, compare with top3 validation mIou, about 72-73, the results I got from pointnext-XL only around 68.8.

Did you try on scannetv2? What's your conclusion? Why the improvements on s3dis seems not work well on scannetv2 or maybe other datasets?

**Comment by lcysonya** [comment]
Many thanks ：）
Looking forward to your follow-up work and wish everything goes well for you.
